import time
import threading
from prometheus_client import (
    start_http_server,
    Counter,
    Histogram,
    Gauge,
    generate_latest,
    CONTENT_TYPE_LATEST,
    CollectorRegistry,
    REGISTRY,
)
from fastapi import Response

# Prometheus metrics
LLM_REQUESTS = Counter("llm_requests_total", "Total LLM requests", ["model", "phase"])
LLM_LATENCY = Histogram("llm_latency_seconds", "LLM latency seconds", ["model", "phase"])
LLM_TOKENS = Counter("llm_tokens_total", "Estimated tokens generated by LLM", ["model"])
LLM_COST = Gauge("llm_cost_total", "Estimated LLM cost (user-provided units)", ["model"])

RETRIEVAL_REQUESTS = Counter("retrieval_requests_total", "Total retrieval requests")
RETRIEVAL_LATENCY = Histogram("retrieval_latency_seconds", "Retrieval latency seconds")
RETRIEVAL_RESULTS = Gauge("retrieval_results_count", "Number of documents returned")

GUARDRAIL_VIOLATIONS = Counter("guardrail_violations_total", "Guardrail violations", ["type"])

# Start a standalone prometheus metrics server on a port (optional)
def start_prometheus_server(port: int = 8000):
    def _start():
        try:
            start_http_server(port)
            print(f"Prometheus metrics server started on :{port}")
        except Exception as e:
            print("Failed to start prometheus server:", e)

    t = threading.Thread(target=_start, daemon=True)
    t.start()

# Attach /metrics to a FastAPI app (alternative to standalone server)
def attach_metrics_endpoint(app, path: str = "/metrics"):
    @app.get(path)
    def metrics():
        data = generate_latest(REGISTRY)
        return Response(content=data, media_type=CONTENT_TYPE_LATEST)

# Helpers to record observations
def observe_llm_call(model: str, phase: str = "generation", latency: float = 0.0, tokens: int = 0, cost: float = 0.0):
    try:
        LLM_REQUESTS.labels(model=model, phase=phase).inc()
        LLM_LATENCY.labels(model=model, phase=phase).observe(latency)
        if tokens:
            LLM_TOKENS.labels(model=model).inc(tokens)
        if cost:
            LLM_COST.labels(model=model).set(cost)
    except Exception:
        pass

def observe_retrieval(latency: float, n_results: int):
    try:
        RETRIEVAL_REQUESTS.inc()
        RETRIEVAL_LATENCY.observe(latency)
        RETRIEVAL_RESULTS.set(n_results)
    except Exception:
        pass

def increment_guardrail(event_type: str):
    try:
        GUARDRAIL_VIOLATIONS.labels(type=event_type).inc()
    except Exception:
        pass